$buttons = [
    'aperture',      
    'shutter speed',
    'iso' ,
    'rule of thirds', 
    'white balance', 
    'depth of field',
    'exposure triangle' ,
    'golden hour',
    'blue hour',
    'bokeh',
    'leading lines' ,
    'long exposure' ,
    'hdr',
    'macro photography',
    'low light photography' ,
    'night photography',
    'street photography',
    'portrait photography' ,
    'wildlife photography' ,
    'landscape photography' ,
    'action photography',
    'black and white photography' ,
    'composition' ,
    'camera sensor',
    'film photography',
    'dslr vs mirrorless',s
];